#!/bin/bash
set -e

DATABASE_HOST=${DATABASE_HOST:-postgres}
DATABASE_PORT=${DATABASE_PORT:-5432}
DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
DATABASE_PASSWORD=${DATABASE_PASSWORD:-}
DATABASE_NAME=${DATABASE_NAME:-postgres}
DATABASE_URI="postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}"

export TRYTOND_DATABASE__URI="${TRYTOND_DATABASE__URI:-"$DATABASE_URI"}"
export TRYTOND_DATABASE__LIST="${TRYTOND_DATABASE_LIST:-False}"
export TRYTOND_WEB__LISTEN="${TRYTOND_WEB__LISTEN:-"0.0.0.0:8000"}"
export TRYTOND_ADMIN_PASSWORD=${TRYTOND_ADMIN_PASSWORD:-admin123}
export TRYTONPASSFILE="/etc/.pass"
echo $TRYTOND_ADMIN_PASSWORD > $TRYTONPASSFILE

# Wait for database
wait-for-it ${DATABASE_HOST}:${DATABASE_PORT}

if [ "$1" = 'trytond' ]; then
    shift
    exec trytond -d $DATABASE_NAME "$@"
else
    exec "$@"
fi

if [ "$1" = 'trytond-admin' ]; then
    rm -f $TRYTONPASSFILE
fi
