#!/bin/bash
set -e

TRYTOND_DATABASE__HOST=${TRYTOND_DATABASE__HOST:-postgres}
TRYTOND_DATABASE__PORT=${TRYTOND_DATABASE__PORT:-5432}
TRYTOND_DATABASE__USERNAME=${TRYTOND_DATABASE__USERNAME:-postgres}
TRYTOND_DATABASE__PASSWORD=${TRYTOND_DATABASE__PASSWORD:-}
TRYTOND_DATABASE__NAME=${TRYTOND_DATABASE__NAME:-postgres}
DATABASE_URI="postgresql://${TRYTOND_DATABASE__USERNAME}:${TRYTOND_DATABASE__PASSWORD}@${TRYTOND_DATABASE__HOST}:${TRYTOND_DATABASE__PORT}/${TRYTOND_DATABASE__NAME}"

export TRYTOND_DATABASE__URI="${TRYTOND_DATABASE__URI:-"$DATABASE_URI"}"
export TRYTOND_DATABASE__LIST="${TRYTOND_DATABASE_LIST:-False}"
export TRYTOND_WEB__LISTEN="${TRYTOND_WEB__LISTEN:-"0.0.0.0:8000"}"
export TRYTOND_ADMIN_PASSWORD=${TRYTOND_ADMIN_PASSWORD:-admin123}
export TRYTONPASSFILE="/etc/.pass"
echo $TRYTOND_ADMIN_PASSWORD > $TRYTONPASSFILE

# Wait for database
wait-for-it ${TRYTOND_DATABASE__HOST}:${TRYTOND_DATABASE__PORT}

if [ "$1" = 'trytond' ]; then
    shift
    exec trytond -d $TRYTOND_DATABASE__NAME "$@"
else
    exec "$@"
fi

if [ "$1" = 'trytond-admin' ]; then
    rm -f $TRYTONPASSFILE
fi
